name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --workspaces --if-present

      - name: Lint
        run: npm run lint --workspaces

      - name: Build
        run: npm run build --workspaces

      - name: Run tests with coverage
        # Pass `--coverage` so jest picks up the config, and `--passWithNoTests` if you need it
        run: npm test --workspaces -- --coverage

      - name: Upload coverage to Codecov  # optional
        if: success()
        uses: codecov/codecov-action@v3
        with:
          files: coverage/lcov.info
